### ISSUE TITLE
Orientation option (vertical vs horizontal)

### ISSUE THREAD

**Issue by lalstef** [nerik/leaflet-graphicscale#6]
Hello,

I think it's a good idea to add an orientation option so the users can choose whether to display the scale vertically or horizontally. Ideally, there will be a switch (small icon) to change the orientation dynamically. I know this is not a measurement plugin, but can be used as such for measuring distance approximately.

I tried setting 'transform: rotate(90deg)' css property to <div class="leaflet-control-graphicscale leaflet-control"> and it just worked. (I know it's a bit more complex that that if you decide to implement this).

Thanks.

**Comment by ghybs** [comment]
Hi,

Actually be careful with vertical scale in default Leaflet CRS (Web Mercator EPSG3857).
Vertical lengths are represented completely differently from horizontal ones in that CRS.

For example, at zoom level 0:
256 pixels represent about 40,000 km horizontally at the equator (the Earth circumference at the equator), but a little bit less than 20,000 km vertically from North edge to South edge. (about 18,900 km actually, because North and South edges are actually cropped at about +/- 85 degrees latitude)

**Comment by nerik** [comment]
Please re-open here if still applicable: https://github.com/kalisio/leaflet-graphicscale/issues
